insert into author (id, Name, birth_date, particularity) values (1, 'Perri', '01/30/2022', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into author (id, Name, birth_date, particularity) values (2, 'Biddy', '10/20/2022', 'Ut tellus.');
insert into author (id, Name, birth_date, particularity) values (3, 'Cherrita', '04/30/2022', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into author (id, Name, birth_date, particularity) values (4, 'Linus', '10/30/2022', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into author (id, Name, birth_date, particularity) values (5, 'Con', '01/27/2022', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into author (id, Name, birth_date, particularity) values (6, 'Averill', '02/13/2022', 'Donec posuere metus vitae ipsum.');
insert into author (id, Name, birth_date, particularity) values (7, 'Thalia', '10/25/2022', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into author (id, Name, birth_date, particularity) values (8, 'Harley', '12/15/2021', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into author (id, Name, birth_date, particularity) values (9, 'Vinnie', '11/08/2022', 'Nullam varius. Nulla facilisi.');
insert into author (id, Name, birth_date, particularity) values (10, 'Gusty', '12/31/2021', 'Cras in purus eu magna vulputate luctus.');
